# Generated by Django 4.1.3 on 2022-11-07 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flip_app', '0002_remove_users_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='password1',
        ),
    ]
