# Generated by Django 4.1.3 on 2022-11-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flip_app', '0003_remove_users_password1'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1),
            preserve_default=False,
        ),
    ]
