# Generated by Django 4.1.3 on 2022-11-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flip_app', '0004_users_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(error_messages={'unique': 'This email already exist'}, max_length=50, unique=True),
        ),
    ]
