# Generated by Django 4.1.3 on 2022-11-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flip_app', '0005_alter_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='token',
            field=models.CharField(default=None, max_length=35),
            preserve_default=False,
        ),
    ]
