# Generated by Django 4.1.3 on 2022-11-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flip_app', '0007_category_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ManyToManyField(related_name='pcategory', to='flip_app.category'),
        ),
    ]
