# Generated by Django 4.1.3 on 2022-11-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flip_app', '0008_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
