# Generated by Django 4.1.3 on 2022-11-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flip_app', '0011_alter_category_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
