# Generated by Django 4.1.3 on 2022-11-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flip_app', '0012_users_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='token',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
